lightblue-platform/lightblue-client

http/src/main/java/com/redhat/lightblue/client/http/auth/HttpClientCertAuth.java
http/src/main/java/com/redhat/lightblue/client/http/auth/SslSocketFactories.java

Had to make changes to both HttpClientCertAuth and SslSocketFactories as they seem to have some duplicated functionality.

fixes #54 - allow a system file to be given for caFilePath and certFilePath

---

core/src/main/java/com/redhat/lightblue/client/response/LightblueResponse.java
http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClient.java
http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClientException.java
http/src/test/java/com/redhat/lightblue/client/http/LightblueHttpClientTest.java

Just look at the second commit, the first is just changing tabs to spaces.
More information is needed when debugging client issues. This PR will provide more information.

Include more information in exception

---

core/src/main/java/com/redhat/lightblue/client/response/LightblueResponse.java
core/src/test/java/com/redhat/lightblue/client/response/TestLightblueResponse.java

Allows client code to easily determine if an error is in the response.

add shortcut to determine if error was returned

---

core/src/main/java/com/redhat/lightblue/client/expression/update/NullRValue.java
core/src/main/java/com/redhat/lightblue/client/expression/update/PathValuePair.java
core/src/main/java/com/redhat/lightblue/client/expression/update/SetUpdate.java
core/src/test/java/com/redhat/lightblue/client/expression/update/NullRValueTest.java
core/src/test/java/com/redhat/lightblue/client/expression/update/PathValuePairTest.java
core/src/test/java/com/redhat/lightblue/client/expression/update/SetUpdateTest.java

SetUpdate $set was also missing quotation marks.

key to PathValuePair was not getting quotation marks

---

pom.xml

...that said, use slf4j-simple for testing. 
Implementations can be found at http://www.slf4j.org/manual.html

The slf4j implementation used should be optional to the consumer of the client.

---

http/pom.xml
http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClient.java
hystrix/pom.xml
hystrix/src/main/java/com/redhat/lightblue/client/hystrix/LightblueHystrixClient.java
hystrix/src/test/java/com/redhat/lightblue/client/hystrix/LightblueHystrixClientTest.java
pom.xml

You provide another lightblue client as an argument along with hystrix command and group keys.
Requires merging PR https://github.com/lightblue-platform/lightblue-core/pull/341 first.
Note that this doesn't build right now.  I get an error building I can't figure out yet.

Fixes #57: added impl of client that uses hystrix commands

---

core/src/main/java/com/redhat/lightblue/client/response/LightblueResponse.java
core/src/test/java/com/redhat/lightblue/client/response/TestLightblueResponse.java

raise an exception on partial responses in addition to error

---

core/src/main/java/com/redhat/lightblue/client/expression/query/ValueQuery.java
core/src/test/java/com/redhat/lightblue/client/expression/query/ValueQueryTest.java

Also added some expression validation logic.

Fixed ValueQuery expressions to allow values with spaces

---

core/src/main/java/com/redhat/lightblue/client/enums/ArrayOperation.java
core/src/main/java/com/redhat/lightblue/client/enums/NaryOperation.java
core/src/main/java/com/redhat/lightblue/client/enums/SortDirection.java
core/src/main/java/com/redhat/lightblue/client/enums/UnaryOperation.java

ensure consistency of enums

---

core/src/main/java/com/redhat/lightblue/client/expression/query/FieldQuery.java
core/src/test/java/com/redhat/lightblue/client/expression/query/FieldQueryTest.java

Adding nary field relational expressions to FieldQuery

---

core/src/main/java/com/redhat/lightblue/client/enums/ExpressionOperation.java
core/src/main/java/com/redhat/lightblue/client/enums/NaryExpressionOperation.java
core/src/main/java/com/redhat/lightblue/client/expression/query/ValueQuery.java

Some tweaks while reviewing https://github.com/lightblue-platform/lightblue-client/pull/79

Minor updates in review

---

http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClient.java
http/src/main/java/com/redhat/lightblue/client/http/LightblueProxyServlet.java

This will help me figure out what which requests need optimization.

When debug is enabled, lightblue http client logs response time

---

core/src/main/java/com/redhat/lightblue/client/PropertiesLightblueClientConfiguration.java

Adding substitution for in-memory lightblue testing.

add substitution ability for property files

---

lightblue-client-test/src/main/java/com/redhat/lightblue/client/test/request/DataDeleteRequestStub.java
lightblue-client-test/src/main/java/com/redhat/lightblue/client/test/request/DataFindRequestStub.java
lightblue-client-test/src/main/java/com/redhat/lightblue/client/test/request/DataInsertRequestStub.java
lightblue-client-test/src/main/java/com/redhat/lightblue/client/test/request/DataSaveRequestStub.java
lightblue-client-test/src/main/java/com/redhat/lightblue/client/test/request/DataUpdateRequestStub.java

Some clean up based on recent changes.

clean up based on recent changes

---

pom.xml

Follow up to https://github.com/lightblue-platform/lightblue-mongo/pull/119

upgrade hystrix

---

lightblue-client-integration-test/pom.xml
lightblue-client-integration-test/src/main/java/com/redhat/lightblue/client/integration/test/AbstractLightblueClientCRUDController.java
pom.xml

Depends on https://github.com/lightblue-platform/lightblue-rest/pull/155
The finishing step for lightblue-platform/lightblue-test-utils#9.

Move client functionality

---

pom.xml

bump jackson version

---

core/src/main/java/com/redhat/lightblue/client/request/AbstractLightblueRequest.java
core/src/test/java/com/redhat/lightblue/client/request/TestAbstractLightblueRequest.java

Right now it's logging things like: 
```Calling data service with lightblueRequest: com.redhat.lightblue.client.request.data.DataFindRequest@4c9aa0ff```

Fixing request body debug logging

---

core/src/main/java/com/redhat/lightblue/client/response/LightblueException.java

The body of the failed response is not being passed on. This will add that to the exception message.

add message text to exception message

---

core/src/main/java/com/redhat/lightblue/client/response/LightblueException.java

No need to use DefaultLightblueResponse when the interface will do.

cleanup LightblueException

---

.travis.yml
http/pom.xml
lightblue-client-integration-test/src/main/java/com/redhat/lightblue/client/integration/test/AbstractLightblueClientCRUDController.java

Downstream changes from https://github.com/lightblue-platform/lightblue-mongo/pull/134

Fixes from upstream changes

---

core/src/main/java/com/redhat/lightblue/client/Query.java

I find myself calling asArray() a lot. Just seems like we should support both. That said, it doesn't matter to me if we convert an array to a collection or vice versa. I don't know if one would be better than the other, so I just picked one.

add collection to Query and/or operators

---

core/src/main/java/com/redhat/lightblue/client/util/ClientConstants.java

fixes #151 - remove GMT translation

---

lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/CountryDAOTest.java
lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/pojo/Country.java
lightblue-client-integration-test/src/test/resources/metadata/country.json

Nothing major here, just some minor changes I noticed while doing something else.

minor housekeeping

---

core/src/main/java/com/redhat/lightblue/client/request/AbstractLightblueRequest.java
core/src/main/java/com/redhat/lightblue/client/request/metadata/MetadataUpdateSchemaStatusRequest.java
core/src/test/java/com/redhat/lightblue/client/request/AbstractLightblueRequestTest.java
core/src/test/java/com/redhat/lightblue/client/request/metadata/TestMetadataUpdateSchemaStatusRequest.java

#108  Updated MetadataUpdateSchemaStatusRequest to allow for setting comment and added testcases to get the restURI. Added an appendToURI method to append a query param to restURI.

Changed MetadataUpdateSchemaStatusRequest to set Comment

---

core/src/main/java/com/redhat/lightblue/client/request/AbstractLightblueRequest.java
core/src/main/java/com/redhat/lightblue/client/request/metadata/MetadataCreateSchemaRequest.java
core/src/main/java/com/redhat/lightblue/client/request/metadata/MetadataGetEntityNamesRequest.java
core/src/main/java/com/redhat/lightblue/client/request/metadata/MetadataUpdateSchemaStatusRequest.java
core/src/test/java/com/redhat/lightblue/client/request/AbstractLightblueRequestTest.java
core/src/test/java/com/redhat/lightblue/client/request/metadata/TestMetadataCreateSchemaRequest.java
core/src/test/java/com/redhat/lightblue/client/request/metadata/TestMetadataGetEntityNamesRequest.java
core/src/test/java/com/redhat/lightblue/client/request/metadata/TestMetadataUpdateSchemaStatusRequest.java

#107 Updated MetadataCreateSchemaRequest to allow definition of required path param schema.
Updated MetadataGetEntityNamesRequest to allow definition of optional path param status.

MetadataRequest update

---

core/src/main/java/com/redhat/lightblue/client/request/metadata/MetadataUpdateSchemaStatusRequest.java
core/src/test/java/com/redhat/lightblue/client/request/metadata/TestMetadataUpdateSchemaStatusRequest.java

I found this bug while working on an unrelated task.

fix issue where comment could not use spaces

---

core/src/main/java/com/redhat/lightblue/client/Projection.java
core/src/main/java/com/redhat/lightblue/client/request/data/DataFindRequest.java
core/src/test/java/com/redhat/lightblue/client/ExpressionTest.java
core/src/test/java/com/redhat/lightblue/client/projection/ProjectionTest.java
core/src/test/java/com/redhat/lightblue/client/request/data/TestDataFindRequest.java

changing type of 'from' and 'to' to Integer to support null values

Support Unbounded range 

---

http/src/test/java/com/redhat/lightblue/client/http/transport/JavaNetHttpTransportIntegrationTest.java

Curious if this fixes travis issues

Use any available port in wiremock tests

---

core/pom.xml
http/pom.xml
hystrix/pom.xml
lightblue-client-integration-test/pom.xml
lightblue-client-test/pom.xml
pom.xml

bump to next major release

---

README.md

Instead of just using the LB overview from core, thought it would be useful to demonstrate how to use the java client libraries on the README.  That's where I usually go first when I'm trying to figure out how to use a library.

add example client usage to README

---

core/src/main/java/com/redhat/lightblue/client/response/AbstractLightblueResponse.java

The response is not going to change once created, no reason to do the work of collecting Error[] or DataError[] multiple times.

no need to do the work multiple times

---

core/src/main/java/com/redhat/lightblue/client/request/data/DataFindRequest.java
lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/data/TestDataFindRequest.java
lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/data/TestDataInsertRequest.java
lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/data/TestDataSaveRequest.java
lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/data/TestDataUpdateRequest.java

- fix bug in DataFindRequest#range
- added new unit test to verify fix
- updated test cases to clear mongo between tests.

fix DataFindRequest#range

---

pom.xml

Working PR to see why hystrix is failing.

Revert and fix "Removing hystrix b/c it breaks java7 build"

---

lightblue-client-integration-test/src/main/java/com/redhat/lightblue/client/integration/test/LightblueExternalResource.java

Depends on https://github.com/lightblue-platform/lightblue-rest/pull/224

make new method available

---

http/src/main/java/com/redhat/lightblue/client/http/transport/JavaNetHttpTransport.java

cleanup seemingly redundant try block

---

core/src/main/java/com/redhat/lightblue/client/request/LightblueRequest.java
core/src/test/java/com/redhat/lightblue/client/request/TestDataFindRequest.java
core/src/test/java/com/redhat/lightblue/client/request/TestDataInsertRequest.java
core/src/test/java/com/redhat/lightblue/client/request/TestDataSaveRequest.java
core/src/test/java/com/redhat/lightblue/client/request/TestDataUpdateRequest.java
http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClient.java

Lightblue request debug logging got broken at some point. Restoring it, it's very helpful when investigating issues in the dev env.

Restore request debug logging

---

core/src/main/java/com/redhat/lightblue/client/response/LightblueBulkResponseException.java
core/src/test/java/com/redhat/lightblue/client/response/TestDefaultLightblueBulkDataResponse.java

https://github.com/lightblue-platform/lightblue-client/issues/315

Include Lightblue responses in LightblueBulkResponseException message

---

core/src/main/java/com/redhat/lightblue/client/request/DataBulkRequest.java
core/src/test/java/com/redhat/lightblue/client/request/data/TestBulkDataRequest.java

For https://github.com/lightblue-platform/lightblue-core/pull/664

Adding ordered flag to bulk request

---

core/src/main/java/com/redhat/lightblue/client/LightblueClientConfiguration.java
core/src/main/java/com/redhat/lightblue/client/PropertiesLightblueClientConfiguration.java
http/src/main/java/com/redhat/lightblue/client/http/auth/SslSocketFactories.java

May be useful in dev environments.
Could use a unit test, but since it's an optional feature intended for dev environments only, I think I can spare the effort.

Adding self signed cert support

---

lightblue-client-integration-test/src/main/java/com/redhat/lightblue/client/integration/test/LightblueClientTestHarness.java
lightblue-client-integration-test/src/main/java/com/redhat/lightblue/client/integration/test/LightblueExternalResource.java
lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/TestLightblueExternalResource.java

Fixes https://github.com/lightblue-platform/lightblue-rest/issues/208
Exposes IdentityManagement to client testing.

Fixes https://github.com/lightblue-platform/lightblue-rest/issues/208

---

core/src/main/java/com/redhat/lightblue/client/Expression.java
core/src/main/java/com/redhat/lightblue/client/LightblueClientConfiguration.java
core/src/main/java/com/redhat/lightblue/client/MongoExecution.java
core/src/main/java/com/redhat/lightblue/client/PropertiesLightblueClientConfiguration.java
core/src/test/java/com/redhat/lightblue/client/MongoExecutionTest.java
core/src/test/java/com/redhat/lightblue/client/request/TestDataFindRequest.java
core/src/test/java/com/redhat/lightblue/client/request/TestDataInsertRequest.java
core/src/test/java/com/redhat/lightblue/client/request/TestDataSaveRequest.java
core/src/test/java/com/redhat/lightblue/client/request/TestDataUpdateRequest.java
http/src/test/java/com/redhat/lightblue/client/http/LightblueHttpClientTest.java

This is to match how readPreference is used.

Adding writeConcern enum

---

http/src/main/java/com/redhat/lightblue/client/http/transport/JavaNetHttpTransport.java
http/src/test/java/com/redhat/lightblue/client/http/transport/JavaNetHttpTransportTest.java
pom.xml

Fix issue with streaming when content length is set on server
