lightblue-platform/lightblue-client

core/src/main/java/com/redhat/lightblue/client/PropertiesLightblueClientConfiguration.java
I was getting a bunch of these exceptions while testing the migrator. This change will ensure that the InputStream is closed when it is finished being read in.
```
[ConsistencyCheckerRunner] ERROR com.redhat.lightblue.client.PropertiesLightblueClientConfiguration - /usr/share/migrator/lightblue-client.properties could not be found/read
java.nio.file.FileSystemException: /usr/share/migrator/lightblue-client.properties: Too many open files
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
at …
```
=> release input stream when done reading

http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClient.java, http/src/test/java/com/redhat/lightblue/client/http/LightblueHttpClientTest.java
It is annoying to get an exception for an empty result set.
=> return null instead of throwing an exception if no processed result is returned

core/src/main/java/com/redhat/lightblue/client/response/LightblueErrorResponseException.java, core/src/main/java/com/redhat/lightblue/client/response/LightblueResponse.java, core/src/test/java/com/redhat/lightblue/client/response/TestLightblueResponse.java
This will create a uniformed way for client application code to deal with errors when they are returned from lb.
=> throw an exception if errors are returned from lb

core/src/main/java/com/redhat/lightblue/client/request/data/DataInsertRequest.java, core/src/main/java/com/redhat/lightblue/client/request/data/DataSaveRequest.java
This caused collections of objects to be processed as single objects, resulting in incorrect lightblue request being generated.
=> Removing create(Collection<Object> objects) apis because they are covered by create(Object... objects)

core/src/main/java/com/redhat/lightblue/client/json/LightBlueJsonHelperImpl.java, core/src/main/java/com/redhat/lightblue/client/response/LightblueResponse.java, core/src/main/java/com/redhat/lightblue/client/util/ClientConstants.java, core/src/main/java/com/redhat/lightblue/client/util/JSON.java, core/src/test/java/com/redhat/lightblue/client/response/TestLightblueResponse.java, http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClient.java
Centralize on a standard default ObjectMapper and allow that to be changed if desired by the client.
=> fixes #65 - standardizes the default ObjectMapper

core/src/main/java/com/redhat/lightblue/client/LightblueClient.java, http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClient.java, http/src/main/java/com/redhat/lightblue/client/http/request/LightblueHttpDataRequest.java, http/src/main/java/com/redhat/lightblue/client/http/request/LightblueHttpMetadataRequest.java, hystrix/src/main/java/com/redhat/lightblue/client/hystrix/LightblueHystrixClient.java, hystrix/src/test/java/com/redhat/lightblue/client/hystrix/LightblueHystrixClientTest.java
The change enforces that only certain LightblueRequest hierarchies are passed into specific LightblueClient methods. As it is, any implementation of LightblueRequest is allowed, but if not of the correct family is essentially ignored. This is first of all confusing, and secondly requires casting if family centric functionality is required.
=> better datatype enforcement

core/src/main/java/com/redhat/lightblue/client/request/AbstractLightblueDataRequest.java, core/src/main/java/com/redhat/lightblue/client/request/AbstractLightblueMetadataRequest.java, core/src/main/java/com/redhat/lightblue/client/request/AbstractLightblueRequest.java, core/src/main/java/com/redhat/lightblue/client/request/data/DataDeleteRequest.java, core/src/main/java/com/redhat/lightblue/client/request/data/DataFindRequest.java, core/src/main/java/com/redhat/lightblue/client/request/data/DataInsertRequest.java, core/src/main/java/com/redhat/lightblue/client/request/data/DataSaveRequest.java, core/src/main/java/com/redhat/lightblue/client/request/data/DataUpdateRequest.java, core/src/main/java/com/redhat/lightblue/client/request/metadata/MetadataClearDefaultVersionRequest.java, core/src/main/java/com/redhat/lightblue/client/request/metadata/MetadataCreateRequest.java, core/src/main/java/com/redhat/lightblue/client/request/metadata/MetadataCreateSchemaRequest.java, core/src/main/java/com/redhat/lightblue/client/request/metadata/MetadataGetEntityDependenciesRequest.java, core/src/main/java/com/redhat/lightblue/client/request/metadata/MetadataGetEntityMetadataRequest.java, core/src/main/java/com/redhat/lightblue/client/request/metadata/MetadataGetEntityNamesRequest.java, core/src/main/java/com/redhat/lightblue/client/request/metadata/MetadataGetEntityRolesRequest.java, core/src/main/java/com/redhat/lightblue/client/request/metadata/MetadataGetEntityVersionsRequest.java, core/src/main/java/com/redhat/lightblue/client/request/metadata/MetadataRemoveEntityRequest.java, core/src/main/java/com/redhat/lightblue/client/request/metadata/MetadataSetDefaultVersionRequest.java, core/src/main/java/com/redhat/lightblue/client/request/metadata/MetadataUpdateEntityInfoRequest.java, core/src/main/java/com/redhat/lightblue/client/request/metadata/MetadataUpdateSchemaStatusRequest.java, core/src/test/java/com/redhat/lightblue/client/request/TestAbstractLightblueDataRequest.java, core/src/test/java/com/redhat/lightblue/client/request/TestAbstractLightblueRequest.java
This fixes an issue where you could call the setBody method, but it would effectively be ignored because getBody was overridden. To me, this is unexpected behaviour and a bug. This also adds a constructor to AbstractLightblueRequest that allows the entityName and entityVersion to be passed up as opposed to implementations having to fend for themselves and creating duplicated logic.
=> Cleanup request structure

http/src/main/java/com/redhat/lightblue/client/http/servlet/AbstractLightblueProxyServlet.java, http/src/test/java/com/redhat/lightblue/client/http/servlet/AbstractLightblueProxyServletTest.java
GET requests work, but other methods fail. I see the content-type header being set in firebug, so I assume the proxy is to blame for not passing it down to lightblue.
=> Setting content-type to 'application/json'

core/src/main/java/com/redhat/lightblue/client/expression/query/ValueQuery.java, core/src/test/java/com/redhat/lightblue/client/expression/query/ValueQueryTest.java
So that it's possible to query by null values. Note that:
```java
withValue("field = null"}
```
will result in
```json
{
"field":"field",
"op":"=",
"rvalue": "null"
}
```
which is a "null", not a null.
To set a null value, you need to use the constructor:
```java
new ValueQuery("field1", ExpressionOperation.EQUALS, null);
```
=> Adding null value support to ValueQuery

core/src/main/java/com/redhat/lightblue/client/response/LightblueException.java, http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClient.java, http/src/test/java/com/redhat/lightblue/client/http/LightblueHttpClientTest.java
I'm a bit concerned this change may break the clients (changes the error handling behavior), but since they already need to be updated because of https://github.com/lightblue-platform/lightblue-client/commit/4630eb23d5e0f4ee7e2864e819526b2edfa2af25, it **should** be ok.
=> Handling IOExceptions properly

lightblue-client-integration-test/src/test/resources/lightblue-crud.json, lightblue-client-integration-test/src/test/resources/mongo-datasources.json, lightblue-client-integration-test/src/test/resources/mongo-lightblue-metadata.json
In order to support changes made in lightblue-mongo, configuration files for tests need to be added to each downstream project.
=> add configs to support changes made in https://github.com/lightblue-platform/lightblue-mongo/pull/135

lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/LockingTest.java, lightblue-client-integration-test/src/test/resources/lightblue-crud.json
Just quickly adding an integration test to verify acquire and release are working via the client.
=> add quick integration test for locking methods acquire and release

lightblue-client-integration-test/src/main/java/com/redhat/lightblue/client/integration/test/BeforeAfterTestRule.java, lightblue-client-integration-test/src/main/java/com/redhat/lightblue/client/integration/test/LightblueExternalResource.java, lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/TestLightblueExternalResource.java
Allows Lightblue to run in-memory as an junit ExternalResource. This is valuable when duel inheritance is a problem.
=> add Lightblue as ExternalResource

core/src/main/java/com/redhat/lightblue/client/Literal.java
Long[] ids = ...
Query.in, Literal.values(ids) 
was causing 
The method values(int...) in the type Literal is not applicable for the arguments (Long[])
=> Use Literal.values with boxed types instead primitives

core/src/main/java/com/redhat/lightblue/client/Literal.java, core/src/test/java/com/redhat/lightblue/client/LiteralTest.java
Client is adding decimal point to literals created from long and lightblue does not like that.
=> Fixing long handling in Literal

lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/BulkDataTest.java, lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/pojo/Country.java
Add a integration test to ensure a bulk request from the client returns responses in the same order as the requests.
=> add sql test for bulk

core/src/main/java/com/redhat/lightblue/client/request/AbstractDataBulkRequest.java
Only needs collection, so ask for collection. More or less the same
reason you don't put ArrayList in the parameter. You don't care what the
type is as long as it's a collection.
In consuming code I am trying to pass a map's keySet which is a Set.
Shouldn't have to convert it to a List first.
=> Should always ask for least specific type you need

pom.xml
Many projects depending on this client do not pull in specific versions of lightblue-core.  Version 1.9.0 has some bugs, this PR is to make sure when next client version is cut we get an updated dependency on core.
=> Updated core version

core/src/main/java/com/redhat/lightblue/client/response/BulkResponseException.java, core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueBulkDataResponse.java, core/src/main/java/com/redhat/lightblue/client/response/LightblueBulkDataErrorResponse.java, core/src/main/java/com/redhat/lightblue/client/response/LightblueBulkDataResponse.java, core/src/main/java/com/redhat/lightblue/client/response/LightblueBulkResponseException.java, core/src/test/java/com/redhat/lightblue/client/response/TestDefaultLightblueBulkDataResponse.java, http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClient.java
See #202 for conversation about this fix.
This is a breaking change as DefaultLightblueBulkDataResponse now throws LightblueBulkResponseException instead of LightblueResponseException.
Also, seq exception now throws a LightblueParseException.
=> Issue #202 - Bulk Data Response now returns all responses reguardless of any lb errors

http/src/main/java/com/redhat/lightblue/client/http/auth/SslSocketFactories.java
See https://github.com/lightblue-platform/lightblue-client/issues/244 for description.  Was simple, so thought I might as well put it out there.
=> use SslSocketFactory's classloader to find classpath certificate resources

core/src/main/java/com/redhat/lightblue/client/LightblueClientConfiguration.java, http/src/main/java/com/redhat/lightblue/client/http/auth/SslSocketFactories.java
The method names for the private/CA cert paths don't really denote that they're supposed to be on the classpath, thought it might be helpful to make that a little more clear (tripped me up for a moment anyway).
Use the Java 7 Objects class to check for null value - let me know if LB has a standard way of doing this or isn't on 7.  Didn't see a source/target java compile version in the parent pom, would be happy to add one though.
=> Add javadocs for client cert locations + more descriptive errors

core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueDataResponse.java, core/src/main/java/com/redhat/lightblue/client/response/LightblueErrorResponse.java
Originally part of #234, I am pulling this change out so it can be approved independently.
=> remove depreciated methods from LightblueErrorResponse

README.md
Added some example code to show how to get at the raw lightblue response via java objects on the README.  Figured it'd be a common FAQ, and it would be useful to have it there.
=> add documentation for how to parse lightblue response entities

lightblue-client-integration-test/pom.xml
Fixes an issue when attempting to run individual tests in an IDE.
=> use jdk8 explicitply for lightblue-client-integration-test

core/src/main/java/com/redhat/lightblue/client/response/AbstractLightblueResponse.java, core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueBulkDataResponse.java, core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueDataResponse.java, core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueMetadataResponse.java, core/src/main/java/com/redhat/lightblue/client/response/LightblueErrorResponse.java, core/src/main/java/com/redhat/lightblue/client/response/LightblueResponse.java, core/src/main/java/com/redhat/lightblue/client/response/LightblueResponseException.java, core/src/main/java/com/redhat/lightblue/client/response/lock/LockResponse.java, core/src/test/java/com/redhat/lightblue/client/response/TestDefaultLightblueBulkDataResponse.java, core/src/test/java/com/redhat/lightblue/client/response/TestDefaultLightblueDataResponse.java, http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClient.java, http/src/main/java/com/redhat/lightblue/client/http/transport/HttpResponse.java, http/src/main/java/com/redhat/lightblue/client/http/transport/HttpTransport.java, http/src/main/java/com/redhat/lightblue/client/http/transport/JavaNetHttpTransport.java, http/src/main/java/com/redhat/lightblue/client/http/transport/Response.java, http/src/test/java/com/redhat/lightblue/client/http/LightblueHttpClientTest.java, http/src/test/java/com/redhat/lightblue/client/http/transport/JavaNetHttpTransportCompressionTest.java, http/src/test/java/com/redhat/lightblue/client/http/transport/JavaNetHttpTransportIntegrationTest.java, http/src/test/java/com/redhat/lightblue/client/http/transport/JavaNetHttpTransportTest.java, lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/CountryDAOTest.java
Makes headers available to client applications and also includes the RequestID in the error message.
=> fixes #317 - add support for RequestID header
